=== ndescussebrown/Data_Pipelines1_project/NDB_touroperator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 	
	targetNamespace="http://NDBtouroperator.fr/myvocabulary#" 
	xmlns:ndb="http://NDBtouroperator.fr/myvocabulary#"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<!-- THIS IS THE XML SCHEMA FOR ALL TOURS OFFERED BY NDBTOUROPERATOR-->
	<xs:element name="TOURS">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="ndb:TOUR"/>
				<xs:element maxOccurs="unbounded" ref="ndb:CONTINENT"/>
				<xs:element maxOccurs="unbounded" ref="ndb:COUNTRY"/>
				<xs:element maxOccurs="unbounded" ref="ndb:TYPE"/>
				<xs:element maxOccurs="unbounded" ref="ndb:BUDGET"/>
				<xs:element maxOccurs="unbounded" ref="ndb:GUIDE"/>
				<xs:element maxOccurs="unbounded" ref="ndb:CLIENT"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="keycontinent">
			<xs:selector xpath="ndb:CONTINENT"/>
			<xs:field xpath="@contid"/>
		</xs:key>
		<xs:keyref name="refcontinent" refer="ndb:keycontinent">
			<xs:selector xpath="ndb:TOUR/ndb:DEST_CONTINENT" />
			<xs:field xpath="@contidref"/>
		</xs:keyref> 
	    <xs:key name="keycountry">
			<xs:selector xpath="ndb:COUNTRY"/>
			<xs:field xpath="@countid"/>
		</xs:key>
		<xs:keyref name="refcountry" refer="ndb:keycountry">
			<xs:selector xpath="ndb:TOUR/ndb:DEST_CONTINENT/ndb:DEST_COUNTRY" />
			<xs:field xpath="@countidref"/>
		</xs:keyref> 
		<xs:key name="keytype">
			<xs:selector xpath="ndb:TYPE"/>
			<xs:field xpath="@typeid"/>
		</xs:key>
		<xs:keyref name="reftype" refer="ndb:keytype">
			<xs:selector xpath="ndb:TOUR/ndb:TOUR_TYPE" />
			<xs:field xpath="@typeidref"/>
		</xs:keyref> 
		<xs:key name="keybudget">
			<xs:selector xpath="ndb:BUDGET"/>
			<xs:field xpath="@budgid"/>
		</xs:key>
		<xs:keyref name="refbudget" refer="ndb:keybudget">
			<xs:selector xpath="ndb:TOUR/ndb:TOUR_BUDGET" />
			<xs:field xpath="@budgidref"/>
		</xs:keyref> 
		<xs:key name="keyguide">
			<xs:selector xpath="ndb:GUIDE"/>
			<xs:field xpath="@guideid"/>
		</xs:key>
		<xs:keyref name="refguide" refer="ndb:keyguide">
			<xs:selector xpath="ndb:TOUR/ndb:INSTANCES/ndb:INSTANCE/ndb:TOURGUIDE" />
			<xs:field xpath="@guideref"/>
		</xs:keyref> 
				<xs:key name="keyclient">
			<xs:selector xpath="ndb:CLIENT"/>
			<xs:field xpath="@clientid"/>
		</xs:key>
		<xs:keyref name="refclient" refer="ndb:keyclient">
			<xs:selector xpath="ndb:TOUR/ndb:INSTANCES/ndb:INSTANCE/ndb:CLIENTS/ndb:TOURCLIENT" />
			<xs:field xpath="@clientref"/>
		</xs:keyref> 
	</xs:element>
	
	<xs:element name="TOUR" type="ndb:TOURtype"/>
	<xs:complexType name="TOURtype">
		<xs:sequence>
			<xs:element ref="ndb:TOURNAME"/>
			<xs:element ref="ndb:DEST_CONTINENT"/>
			<xs:element ref="ndb:TOUR_TYPE"/>
			<xs:element ref="ndb:DURATION"/>
			<xs:element ref="ndb:INSTANCES"/>
			<xs:element ref="ndb:FLIGHTS"/>
			<xs:element ref="ndb:TRANSFERS"/>
			<xs:element ref="ndb:TOUR_BUDGET"/>
			<xs:element ref="ndb:RATINGS"/>
			<xs:element ref="ndb:DESCRIPTION"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="INSTANCES" type="ndb:INSTANCEStype"/>
	<xs:complexType name="INSTANCEStype">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" ref="ndb:INSTANCE"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="INSTANCE" type="ndb:INSTANCEtype"/>
	<xs:complexType name="INSTANCEtype">
		<xs:sequence>
			<xs:element ref="ndb:START_DATE"/>
			<xs:element ref="ndb:PRICE"/>
			<xs:element ref="ndb:TOURGUIDE"/>
			<xs:element ref="ndb:CLIENTS"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="TOURNAME" type="xs:string"/> 
	
	<xs:element name="DEST_CONTINENT" type="ndb:DEST_CONTtype"/>
	<xs:complexType name="DEST_CONTtype">
			<xs:sequence>
				<xs:element ref="ndb:DEST_COUNTRY"/>
			</xs:sequence>
			<xs:attribute name="contidref" use="required" type="xs:string"/>
	</xs:complexType>
	
	<xs:element name="TOUR_TYPE">
		<xs:complexType>
			<xs:attribute name="typeidref" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="DEST_COUNTRY">
		<xs:complexType>
			<xs:attribute name="countidref" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="TOUR_BUDGET">
		<xs:complexType>
			<xs:attribute name="budgidref" use="required" type="xs:string"/>
	</xs:complexType>
	</xs:element>
	
	<xs:element name="TOURGUIDE">
		<xs:complexType>
			<xs:attribute name="guideref" use="required" type="xs:string"/>
	</xs:complexType>
	</xs:element>
	
	
	<xs:element name="CLIENTS" type="ndb:Clientstype"/>
	<xs:complexType name="Clientstype">
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="ndb:TOURCLIENT"/>
			</xs:sequence>
	</xs:complexType>
	
	<xs:element name="TOURCLIENT">
	<xs:complexType>
			<xs:attribute name="clientref" use="required" type="xs:string"/>
	</xs:complexType>
	</xs:element>
	
	<xs:element name="DESCRIPTION" type="xs:string"/>
	<xs:element name="START_DATE" type="xs:date"/>
	<xs:element name="FLIGHTS" type="xs:boolean"/>
	<xs:element name="TRANSFERS" type="xs:boolean"/>
	<xs:element name="DURATION" type="xs:string"/> 
	<xs:element name="PRICE" type="xs:integer"/> 
	
	<xs:element name="RATINGS" type="ndb:RATINGStype" /> 
	<xs:complexType name="RATINGStype">
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="ndb:RATING"/>
			</xs:sequence>
	</xs:complexType>

	
	
	<xs:element name="RATING" type="xs:decimal"/> 
	
	<xs:element name="CONTINENT" type='ndb:Continenttype'/>
	<xs:complexType name='Continenttype'>
		<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="contid" use="required" type="xs:string"/>
				</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:element name="COUNTRY" type='ndb:Countrytype' />
	<xs:complexType name='Countrytype'>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="countid" use="required" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
	</xs:complexType>
	
	<xs:element name="TYPE" type='ndb:Typetype'/>
	<xs:complexType name='Typetype'>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="typeid" use="required" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
	</xs:complexType>
	
	<xs:element name="BUDGET" type='ndb:Budgettype'/>
	<xs:complexType name='Budgettype'>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="budgid" use="required" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
	</xs:complexType>

	<xs:element name="GUIDE" type='ndb:Guidetype'/>
	<xs:complexType name='Guidetype'>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="guideid" use="required" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
	</xs:complexType>
	
	
	<xs:element name="CLIENT">
	<xs:complexType>
			<xs:sequence>
				<xs:element ref="ndb:CLIENTLASTNAME"/>
				<xs:element ref="ndb:CLIENTFIRSTNAME"/>
			</xs:sequence>
			<xs:attribute name="clientid" use="required" type="xs:string"/>
	</xs:complexType>
	</xs:element>
	<xs:element name="CLIENTLASTNAME" type="xs:string"/> 
	<xs:element name="CLIENTFIRSTNAME" type="xs:string"/> 
	
</xs:schema>

=== ndescussebrown/Data_Pipelines1_project/NDB_touroperator.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="NDB_touroperator_avgrating.xsl"?> 
<!-- THIS IS THE DATABASE FOR ALL TOURS OFFERED BY NDBTOUROPERATOR-->
<ndb:TOURS 
	xmlns:ndb="http://NDBtouroperator.fr/myvocabulary#" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://NDBtouroperator.fr/myvocabulary#  NDB_touroperator.xsd">
	<ndb:TOUR>
		<ndb:TOURNAME>Darwin to Sydney</ndb:TOURNAME>
		<ndb:DEST_CONTINENT contidref="con5">
			<ndb:DEST_COUNTRY countidref="con51" />
		</ndb:DEST_CONTINENT>
		<ndb:TOUR_TYPE typeidref="t3"/>
		<ndb:DURATION>16 days</ndb:DURATION>
		<ndb:INSTANCES>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-02-24</ndb:START_DATE>
				<ndb:PRICE>2799</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g1" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl1" />
					<ndb:TOURCLIENT clientref="cl3" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-05-13</ndb:START_DATE>
				<ndb:PRICE>2959</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g2" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl2" />
					<ndb:TOURCLIENT clientref="cl4" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
		</ndb:INSTANCES>
		<ndb:FLIGHTS>1</ndb:FLIGHTS>
		<ndb:TRANSFERS>1</ndb:TRANSFERS>
		<ndb:TOUR_BUDGET budgidref="b1" />
		<ndb:RATINGS>
			<ndb:RATING>2</ndb:RATING><ndb:RATING>3</ndb:RATING><ndb:RATING>2.5</ndb:RATING>
		</ndb:RATINGS>
		<ndb:DESCRIPTION>This tours the East coast of Australia and will take you from Darwin to Sydney via Brisbane and the sandy beaches of the Gold Coast. A one in a lifetime adventure!</ndb:DESCRIPTION>
	</ndb:TOUR>
	<ndb:TOUR>
		<ndb:TOURNAME>Winetasting in Italy</ndb:TOURNAME>
		<ndb:DEST_CONTINENT contidref="con4">
			<ndb:DEST_COUNTRY countidref="con41" />
		</ndb:DEST_CONTINENT>
		<ndb:TOUR_TYPE typeidref="t2"/>
		<ndb:DURATION>8 days</ndb:DURATION>
		<ndb:INSTANCES>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-03-23</ndb:START_DATE>
				<ndb:PRICE>1099</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g4" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl5" />
					<ndb:TOURCLIENT clientref="cl6" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-06-17</ndb:START_DATE>
				<ndb:PRICE>1359</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g5" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl8" />
					<ndb:TOURCLIENT clientref="cl7" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-08-29</ndb:START_DATE>
				<ndb:PRICE>1599</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g4" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl10" />
					<ndb:TOURCLIENT clientref="cl9" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
		</ndb:INSTANCES>
		<ndb:FLIGHTS>0</ndb:FLIGHTS>
		<ndb:TRANSFERS>1</ndb:TRANSFERS>
		<ndb:TOUR_BUDGET budgidref="b2" />
		<ndb:RATINGS>
			<ndb:RATING>4</ndb:RATING><ndb:RATING>5</ndb:RATING><ndb:RATING>4.5</ndb:RATING>
		</ndb:RATINGS>
		<ndb:DESCRIPTION>This tours will take you through the Chianti area of Italy where we will take you through some amazing vineyards and taste some of the world's most fantastic wines. We will also have the pleasure to pair the wines with some of the best of Tuscan cuisine</ndb:DESCRIPTION>
	</ndb:TOUR>
	<ndb:TOUR>
		<ndb:TOURNAME>Boston by Foot</ndb:TOURNAME>
		<ndb:DEST_CONTINENT contidref="con1">
			<ndb:DEST_COUNTRY countidref="con11" />
		</ndb:DEST_CONTINENT>
		<ndb:TOUR_TYPE typeidref="t10"/>
		<ndb:DURATION>5 days</ndb:DURATION>
		<ndb:INSTANCES>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-04-15</ndb:START_DATE>
				<ndb:PRICE>899</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g6" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl4" />
					<ndb:TOURCLIENT clientref="cl6" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-08-08</ndb:START_DATE>
				<ndb:PRICE>1249</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g5" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl3" />
					<ndb:TOURCLIENT clientref="cl2" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
		</ndb:INSTANCES>
		<ndb:FLIGHTS>0</ndb:FLIGHTS>
		<ndb:TRANSFERS>0</ndb:TRANSFERS>
		<ndb:TOUR_BUDGET budgidref="b1" />
		<ndb:RATINGS>
			<ndb:RATING>2</ndb:RATING><ndb:RATING>1</ndb:RATING><ndb:RATING>3.5</ndb:RATING>
		</ndb:RATINGS>
		<ndb:DESCRIPTION>This tours will get you to explore the fabulous American city of Boston by foot. Our local guide will get you to cover a lots of ground, from the Seaport neighborhood to the famous Harvard Square and you will get the opportunity to visit the Museum of Fine Arts, take a walk over the Charles River to MIT and even attend a local Redsox baseball game. You will quickly feel like a local!</ndb:DESCRIPTION>
	</ndb:TOUR>
	<ndb:TOUR>
		<ndb:TOURNAME>Cruising the Caribbean</ndb:TOURNAME>
		<ndb:DEST_CONTINENT contidref="con1">
			<ndb:DEST_COUNTRY countidref="con12" />
		</ndb:DEST_CONTINENT>
		<ndb:TOUR_TYPE typeidref="t9"/>
		<ndb:DURATION>14 days</ndb:DURATION>
		<ndb:INSTANCES>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-05-03</ndb:START_DATE>
				<ndb:PRICE>2599</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g6" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl7" />
					<ndb:TOURCLIENT clientref="cl4" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-09-14</ndb:START_DATE>
				<ndb:PRICE>2499</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g5" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl1" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
		</ndb:INSTANCES>
		<ndb:FLIGHTS>1</ndb:FLIGHTS>
		<ndb:TRANSFERS>1</ndb:TRANSFERS>
		<ndb:TOUR_BUDGET budgidref="b3" />
		<ndb:RATINGS>
			<ndb:RATING>5</ndb:RATING><ndb:RATING>5</ndb:RATING><ndb:RATING>4.5</ndb:RATING>
		</ndb:RATINGS>
		<ndb:DESCRIPTION>This cruise will provide some well deserved relaxation as everything will provided for you and all you will need to do as we sail from Montserrat to St Lucia will be to enjoy the sights from your lounger! We have arranged for some stops with the local guides that will give you tours of the islands</ndb:DESCRIPTION>
	</ndb:TOUR>
	<ndb:TOUR>
		<ndb:TOURNAME>Family Disneyland</ndb:TOURNAME>
		<ndb:DEST_CONTINENT contidref="con1">
			<ndb:DEST_COUNTRY countidref="con11" />
		</ndb:DEST_CONTINENT>
		<ndb:TOUR_TYPE typeidref="t7"/>
		<ndb:DURATION>7 days</ndb:DURATION>
		<ndb:INSTANCES>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-02-12</ndb:START_DATE>
				<ndb:PRICE>2099</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g6" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl4" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-05-29</ndb:START_DATE>
				<ndb:PRICE>2399</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g5" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl7" />
					<ndb:TOURCLIENT clientref="cl8" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
		</ndb:INSTANCES>
		<ndb:FLIGHTS>1</ndb:FLIGHTS>
		<ndb:TRANSFERS>1</ndb:TRANSFERS>
	    <ndb:TOUR_BUDGET budgidref="b2" />
		<ndb:RATINGS>
			<ndb:RATING>5</ndb:RATING><ndb:RATING>4</ndb:RATING><ndb:RATING>5</ndb:RATING><ndb:RATING>4.5</ndb:RATING>
		</ndb:RATINGS>
		<ndb:DESCRIPTION>Your chance to experience Disneyland as a VIP. Little ang big ones will have tons of funs on the rides and get to meet all Disney characters in person. A family holiday for all to remember!</ndb:DESCRIPTION>
	</ndb:TOUR>
	<ndb:TOUR>
		<ndb:TOURNAME>Family Seaworld and Australia Zoo</ndb:TOURNAME>
		<ndb:DEST_CONTINENT contidref="con5">
			<ndb:DEST_COUNTRY countidref="con51" />
		</ndb:DEST_CONTINENT>
		<ndb:TOUR_TYPE typeidref="t7"/>
		<ndb:DURATION>14 days</ndb:DURATION>
		<ndb:INSTANCES>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-06-17</ndb:START_DATE>
				<ndb:PRICE>2799</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g6" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl2" />
					<ndb:TOURCLIENT clientref="cl4" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-11-25</ndb:START_DATE>
				<ndb:PRICE>2999</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g5" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl5" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
		</ndb:INSTANCES>
		<ndb:FLIGHTS>1</ndb:FLIGHTS>
		<ndb:TRANSFERS>1</ndb:TRANSFERS>
		<ndb:TOUR_BUDGET budgidref="b2" />
		<ndb:RATINGS>
			<ndb:RATING>5</ndb:RATING><ndb:RATING>5</ndb:RATING><ndb:RATING>5</ndb:RATING>
		</ndb:RATINGS>
		<ndb:DESCRIPTION>Come to Australia to meet animals you would see nowhere else. Our trip will start with Australia Zoo where you will meet the local kangaroos, wombats and wallabies. Then it's off to Seaworld to swim with dolphins before spending some time relaxing on the sandy beaches of the sunshine coast. What's not to love!</ndb:DESCRIPTION>
	</ndb:TOUR>
	<ndb:TOUR>
		<ndb:TOURNAME>Family Ski Trip</ndb:TOURNAME>
		<ndb:DEST_CONTINENT contidref="con4">
			<ndb:DEST_COUNTRY countidref="con42" />
		</ndb:DEST_CONTINENT>
		<ndb:TOUR_TYPE typeidref="t7"/>
		<ndb:DURATION>7 days</ndb:DURATION>
		<ndb:INSTANCES>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-02-11</ndb:START_DATE>
				<ndb:PRICE>1599</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g6" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl1" />
					<ndb:TOURCLIENT clientref="cl3" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
			<ndb:INSTANCE>
				<ndb:START_DATE>2022-04-04</ndb:START_DATE>
				<ndb:PRICE>1379</ndb:PRICE>
				<ndb:TOURGUIDE guideref="g5" />
				<ndb:CLIENTS>
					<ndb:TOURCLIENT clientref="cl1" />
					<ndb:TOURCLIENT clientref="cl3" />
				</ndb:CLIENTS>
			</ndb:INSTANCE>
		</ndb:INSTANCES>
		<ndb:FLIGHTS>0</ndb:FLIGHTS>
		<ndb:TRANSFERS>1</ndb:TRANSFERS>
		<ndb:TOUR_BUDGET budgidref="b2" />
		<ndb:RATINGS>
			<ndb:RATING>4</ndb:RATING><ndb:RATING>3.5</ndb:RATING>
		</ndb:RATINGS>
		<ndb:DESCRIPTION></ndb:DESCRIPTION>
	</ndb:TOUR>
	
	<ndb:CONTINENT contid="con1">America</ndb:CONTINENT>
	<ndb:CONTINENT contid="con2">Africa</ndb:CONTINENT>	
	<ndb:CONTINENT contid="con3">Asia</ndb:CONTINENT>
	<ndb:CONTINENT contid="con4">Europe</ndb:CONTINENT>
